//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int GradesId { get; set; }
        public int EnrollmentId { get; set; }
        public double Midterm { get; set; }
        public double Final { get; set; }
        public double Average { get; set; }
    
        public virtual Enrollments Enrollments { get; set; }
    }
}
